name: Test
on:
  push:
    branches:
      - main
    paths:
      - "**.raku"
  pull_request:
    branches:
      - main
    paths:
      - "**.raku"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # check out our code
      - uses: actions/checkout@v2.4.0
      - uses: actions/checkout@v2.4.0
        with:
          repository: munificent/craftinginterpreters
          path: craftinginterpreters
      - uses: Raku/setup-raku@v1
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - name: Uncomment code
        run: raku ../uncomment.raku c/*.c c/*.h
        working-directory: ./craftinginterpreters
      - name: Test clox
        run: |
          make get
          make test_clox
        working-directory: ./craftinginterpreters
