name: Test jlox and clox
on:
  push:
    branches:
      - main
    paths:
      - "*.raku"
  pull_request:
    branches:
      - main
    paths:
      - "*.raku"
  workflow_dispatch:
jobs:
  test_jlox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: munificent/craftinginterpreters
          path: craftinginterpreters
      - uses: Raku/setup-raku@v1
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - name: Uncomment code
        run: raku ../uncomment.raku $(find java -name "*.java")
        working-directory: ./craftinginterpreters
      - name: Test jlox
        run: |
          make get
          mkdir -p build/debug/cloxd
          make test_jlox
        working-directory: ./craftinginterpreters
  test_clox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: munificent/craftinginterpreters
          path: craftinginterpreters
      - uses: Raku/setup-raku@v1
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - name: Uncomment code
        run: raku ../uncomment.raku c/*.c c/*.h
        working-directory: ./craftinginterpreters
      - name: Test clox
        run: |
          make get
          make test_clox
        working-directory: ./craftinginterpreters
