name: Test
on:
  schedule:
    - cron: "0 16 * * */7" # https://crontab.guru/#0_16_*_*_*/7
  push:
    branches: [main]
    paths:
      - "**.raku"
  pull_request:
    branches: [main]
    paths:
      - "**.raku"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # check out our code
      - uses: actions/checkout@v2.3.4
      - uses: actions/checkout@v2.3.4
        with:
          repository: munificent/craftinginterpreters
          path: craftinginterpreters
      - uses: Raku/setup-raku@v1
      # craftinginterpreters' `make test_clox' depends on a beta version of Dart.
      - uses: cedx/setup-dart@v2.5.0
        with:
          release-channel: beta
      - name: Uncomment code
        run: raku ../uncomment.raku c/*.c c/*.h
        working-directory: ./craftinginterpreters
      - name: Test clox
        run: |
          make get
          make test_clox
        working-directory: ./craftinginterpreters
