name: Test
on:
  schedule:
    - cron: "0 17 * * */7" # https://crontab.guru/#0_17_*_*_*/7
  push:
    branches: [main]
    paths:
      - "**.pl"
  pull_request:
    branches: [main]
    paths:
      - "**.pl"
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: munificent/craftinginterpreters
          path: craftinginterpreters
      - uses: shogo82148/actions-setup-perl@v1
      # craftinginterpreters' `make test' depends on Dart.
      - uses: cedx/setup-dart@v2
      - name: Uncomment code
        run: perl ../uncomment.pl c/*.c c/*.h
        working-directory: ./craftinginterpreters
      - name: Test clox
        run: make test
